#!/bin/bash

# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Regenerate the committed pylock.toml from _pyproject.toml.
#
# The dependency set for this example lives in `_pyproject.toml` (named with a
# leading underscore so it does not look like a real project to build tooling).
# uv only discovers a project file named `pyproject.toml`, so we copy it into a
# scratch directory, resolve a lockfile there, and export it to PEP 751 format.
#
# `--no-emit-project` drops the (empty) root project from the export, leaving only
# the third-party dependencies, the same flag you use to export a uv workspace
# lock into a standalone pylock.toml.
#
# Run this after editing _pyproject.toml, then commit the updated pylock.toml.

set -euo pipefail

if ! command -v uv >/dev/null 2>&1; then
    echo "error: uv is not installed. See https://docs.astral.sh/uv/" >&2
    exit 1
fi

# Resolve paths relative to this script so it works from any working directory.
here=$(dirname "$(readlink -f "$0")")

scratch=$(mktemp -d)
trap 'rm -rf "$scratch"' EXIT

cp "$here/_pyproject.toml" "$scratch/pyproject.toml"

uv lock --directory "$scratch"
uv export --directory "$scratch" \
    --frozen \
    --no-emit-project \
    --format pylock.toml \
    -o pylock.toml

# uv stamps the export command, including the ephemeral scratch path, into a
# header comment. Rewrite that to a stable comment so re-running the script does
# not produce a spurious diff on the temp directory name.
{
    echo "# This file is generated by regenerate_lockfile.sh from _pyproject.toml."
    echo "# Do not edit by hand; edit _pyproject.toml and rerun the script."
    grep -v '^#' "$scratch/pylock.toml"
} > "$here/pylock.toml"

echo "Wrote $here/pylock.toml"
