name: "helloworld-conda"
version: "1.0.0"
description: "Custom venv creation."

build_config:
  base_image: "condaforge/miniforge3:latest"
  package_data:
   - [build_python_venv.sh, build_python_venv.sh]
