name: jax-fem-env
channels:
  - conda-forge
dependencies:
  - python==3.13
  - numpy==2.4.3
  - scipy==1.17.1
  - matplotlib==3.10.8
  - meshio==5.3.5
  - petsc4py==3.25.0
  - gmsh==4.15.2
  - python-gmsh==4.15.2
  - pip
  - pip:
      - setuptools
      - wheel
      - fenics-basix==0.10.0
      - pyfiglet==1.0.4
      - jax[cpu]==0.9.2
      - jax-fem==0.0.11
