services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    restart: unless-stopped
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5000
    networks:
      - multi-tesseract-network
    ports:
      - "5000:5000"

# We create the network here once for all tesseracts.
# This is to avoid creating it multiple times in subsequent docker-compose up commands.
networks:
  multi-tesseract-network:
    name: multi-tesseract-network
