# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for {{name}}
# Generated by tesseract {{version}} on {{timestamp}}

from pathlib import Path
from typing import Any

from juliacall import Main as jl
from pydantic import BaseModel

from tesseract_core.runtime import Array, Differentiable, Float64
from tesseract_core.runtime.julia_recipes import julia_apply, julia_jvp, julia_vjp

# Load the Julia function `apply_jl` (see julia/apply.jl for its contract)
jl.include(str(Path(__file__).parent / "julia" / "apply.jl"))


#
# Schemata
#


class InputSchema(BaseModel):
    x: Differentiable[Array[(None,), Float64]]


class OutputSchema(BaseModel):
    y: Differentiable[Array[(None,), Float64]]


#
# Required endpoints
#


def apply(inputs: InputSchema) -> OutputSchema:
    return OutputSchema(**julia_apply(jl.apply_jl, inputs))


def abstract_eval(abstract_inputs):
    """Calculate output shapes from input shapes.

    Must be implemented explicitly since shapes cannot be traced through Julia code.
    """
    inp = abstract_inputs.model_dump()
    return {
        "y": {"shape": inp["x"]["shape"], "dtype": inp["x"]["dtype"]},
    }


#
# Enzyme-handled gradient endpoints (no need to modify)
#


def jacobian_vector_product(
    inputs: InputSchema,
    jvp_inputs: set[str],
    jvp_outputs: set[str],
    tangent_vector: dict[str, Any],
):
    return julia_jvp(jl.apply_jl, inputs, jvp_inputs, jvp_outputs, tangent_vector)


def vector_jacobian_product(
    inputs: InputSchema,
    vjp_inputs: set[str],
    vjp_outputs: set[str],
    cotangent_vector: dict[str, Any],
):
    return julia_vjp(jl.apply_jl, inputs, vjp_inputs, vjp_outputs, cotangent_vector)
