# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for {{name}}
# Generated by tesseract {{version}} on {{timestamp}}

from typing import Any

import equinox as eqx
from pydantic import BaseModel

from tesseract_core.runtime import Differentiable, Float32
from tesseract_core.runtime.gradient_recipes import (
    jax_abstract_eval,
    jax_apply,
    jax_jacobian,
    jax_jvp,
    jax_vjp,
)

#
# Cache configuration
#
# apply() runs jax.vjp internally and caches the resulting backward function.
# A subsequent vector_jacobian_product call on the same inputs reuses that
# backward, skipping the redundant forward pass that vjp would otherwise repeat.
#
# Under typical tesseract-jax usage (gradient-based code calling the Tesseract
# through tesseract-jax's custom_vjp), apply() runs first on every gradient
# evaluation — even under plain jax.grad — so the cache reliably hits on the
# subsequent vjp call. This makes the recipe close to a free win for any
# gradient-based workflow: Adam/SGD, L-BFGS / line search, value_and_grad-style
# code, etc. Typical speedup is ~10-20% on moderate-to-deep networks.
#
# The cache also helps when a single apply is followed by multiple vjp calls
# on the same input — for example, jax.jacrev (which decomposes into one vjp
# per output basis vector) or CG-style inverse-problem solvers (each inner CG
# step computes J^T u at the same iterate). Each subsequent vjp on the same
# input reuses the cached residuals.
#
# Poor fit:
#   - Very small models where the forward pass is microseconds: the cache
#     machinery overhead exceeds the saved work.
#
# Uncomment to disable caching entirely (apply() and vjp() then bypass the
# cache machinery and run their forward passes directly), or to increase the
# size for workloads that interleave several apply() calls before their
# corresponding vjp() calls.
#
# from tesseract_core.runtime.gradient_recipes import set_jax_cache_size
# set_jax_cache_size(0)

#
# Schemata
#


# Note: This template uses equinox filter_jit to automatically treat non-array
# inputs/outputs as static. As Tesseract scalar objects (e.g. Float32) are
# essentially just wrappers around numpy 0D arrays, they will be considered to
# be dynamic and will be traced by JAX.
# If you want to treat scalar numerical values as static you will need to use
# built-in Python types (e.g. float, int) instead of Float32.


class InputSchema(BaseModel):
    example: Differentiable[Float32]


class OutputSchema(BaseModel):
    example: Differentiable[Float32]


#
# Required endpoints
#


# TODO: Add or import your function here, must be JAX-jittable and
# take/return a single pytree as an input/output conforming respectively
# to Input/OutputSchema
@eqx.filter_jit
def apply_jit(inputs: dict) -> dict:
    return inputs


def apply(inputs: InputSchema) -> OutputSchema:
    # Optional: Insert any pre-processing/setup that doesn't require tracing
    # and is only required when specifically running your apply function
    # and not your differentiable endpoints.
    # For example, you might want to set up a logger or mlflow server.
    # Pre-processing should not modify any input that could impact the
    # differentiable outputs in a nonlinear way (a constant shift
    # should be safe)

    out = jax_apply(apply_jit, inputs)

    # Optional: Insert any post-processing that doesn't require tracing
    # For example, you might want to save to disk or modify a non-differentiable
    # output. Again, do not modify any differentiable output in a non-linear way.
    return out


#
# Jax-handled gradient endpoints (no need to modify)
#


def jacobian(
    inputs: InputSchema,
    jac_inputs: set[str],
    jac_outputs: set[str],
):
    return jax_jacobian(apply_jit, inputs, jac_inputs, jac_outputs)


def jacobian_vector_product(
    inputs: InputSchema,
    jvp_inputs: set[str],
    jvp_outputs: set[str],
    tangent_vector: dict[str, Any],
):
    return jax_jvp(apply_jit, inputs, jvp_inputs, jvp_outputs, tangent_vector)


def vector_jacobian_product(
    inputs: InputSchema,
    vjp_inputs: set[str],
    vjp_outputs: set[str],
    cotangent_vector: dict[str, Any],
):
    return jax_vjp(apply_jit, inputs, vjp_inputs, vjp_outputs, cotangent_vector)


def abstract_eval(abstract_inputs):
    return jax_abstract_eval(apply_jit, abstract_inputs)
