# Copyright 2025 Pasteur Labs. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tesseract API module for {{name}}
# Generated by tesseract {{version}} on {{timestamp}}

from typing import Any

import equinox as eqx
import jax
import jax.numpy as jnp
from jax.tree_util import Partial
from pydantic import BaseModel

from tesseract_core.runtime import Differentiable, Float32
from tesseract_core.runtime.tree_transforms import (
    LRUCache,
    filter_func,
    flatten_with_paths,
    hash_pytree_leaves,
)

#
# Cache configuration
#
# This recipe caches the linearization of apply() so that gradient endpoints
# (vjp, jvp, jacobian) can reuse the forward pass instead of recomputing it.
#
# Best fit:
#   - Iterative solvers that evaluate many JVPs at the same point, e.g. CG for
#     an inverse problem (the linear map is evaluated hundreds of times per solve).
#   - Line-search optimizers such as L-BFGS, which call apply() one or more
#     times before accepting a step and requesting a gradient.
#   - Any workflow that calls apply() and then a gradient endpoint on the same
#     inputs — the cache saves the repeated forward pass (~40% on a typical call).
#
# Poor fit:
#   - Optimizers that only ever use gradient information and never inspect the
#     loss value (e.g. Adam/SGD using jax.grad rather than jax.value_and_grad).
#     No apply() call is issued, the cache is never populated, and every vjp
#     pays a cold-miss linearize cost. Use --recipe jax instead.
#
# _CACHE_SIZE = 1 covers the common case (one outstanding apply at a time).
# Increase it if your workflow interleaves multiple apply() calls before their
# corresponding gradient calls.
#
_CACHE_SIZE = 1

#
# Schemata
#


# Note: This template uses equinox filter_jit to automatically treat non-array
# inputs/outputs as static. As Tesseract scalar objects (e.g. Float32) are
# essentially just wrappers around numpy 0D arrays, they will be considered to
# be dynamic and will be traced by JAX.
# If you want to treat scalar numerical values as static you will need to use
# built-in Python types (e.g. float, int) instead of Float32.


class InputSchema(BaseModel):
    example: Differentiable[Float32]


class OutputSchema(BaseModel):
    example: Differentiable[Float32]


#
# Internals — no need to modify below this line
#
_cache = LRUCache(maxsize=_CACHE_SIZE)
_f_lin_ref: dict[tuple, Partial] = {}


def _hash_inputs(inputs_dict: dict) -> bytes:
    """Compute a SHA-256 hash of a pytree of inputs for cache key comparison."""
    leaves, treedef = jax.tree.flatten(inputs_dict)
    return hash_pytree_leaves(leaves, treedef)


def _shape_key(inputs_dict: dict) -> tuple:
    """Shape/dtype key used to share one linearization reference per input shape."""
    leaves, treedef = jax.tree.flatten(eqx.filter(inputs_dict, eqx.is_array))
    return (str(treedef), tuple((leaf.shape, str(leaf.dtype)) for leaf in leaves))


def _linearize_and_cache(inputs_dict: dict) -> tuple:
    """Return (primal_out, f_lin) for *inputs_dict*, populating the cache on miss.

    f_lin is linearized only over the dynamic (array) inputs so that non-array
    leaves (e.g. ints, strings) don't show up in the tangent structure.
    """
    key = _hash_inputs(inputs_dict)
    hit = _cache.get(key)
    if hit is not None:
        return hit

    dynamic_in, static_in = eqx.partition(inputs_dict, eqx.is_array)

    def _apply_dynamic_only(dyn):
        out = apply_jit(eqx.combine(dyn, static_in))
        dynamic_out, _ = eqx.partition(out, eqx.is_array)
        return dynamic_out

    dynamic_primals, f_lin_fresh = jax.linearize(_apply_dynamic_only, dynamic_in)

    ref = _f_lin_ref.setdefault(_shape_key(inputs_dict), f_lin_fresh)
    f_lin = Partial(ref.func, *f_lin_fresh.args)

    full_out = apply_jit(inputs_dict)
    _, static_out = eqx.partition(full_out, eqx.is_array)
    primal_out = eqx.combine(dynamic_primals, static_out)

    entry = (primal_out, f_lin)
    _cache.put(key, entry)
    return entry


#
# Required endpoints
#


# TODO: Add or import your function here, must be JAX-jittable and
# take/return a single pytree as an input/output conforming respectively
# to Input/OutputSchema
@eqx.filter_jit
def apply_jit(inputs: dict) -> dict:
    return inputs


def apply(inputs: InputSchema) -> OutputSchema:
    # Optional: Insert any pre-processing/setup that doesn't require tracing
    # and is only required when specifically running your apply function
    # and not your differentiable endpoints.
    # For example, you might want to set up a logger or mlflow server.
    # Pre-processing should not modify any input that could impact the
    # differentiable outputs in a nonlinear way (a constant shift
    # should be safe)

    if _CACHE_SIZE <= 0:
        out = apply_jit(inputs.model_dump())
    else:
        primal_out, _f_lin = _linearize_and_cache(inputs.model_dump())
        out = primal_out

    # Optional: Insert any post-processing that doesn't require tracing
    # For example, you might want to save to disk or modify a non-differentiable
    # output. Again, do not modify any differentiable output in a non-linear way.
    return out


#
# Jax-handled gradient endpoints (no need to modify)
#


def jacobian(
    inputs: InputSchema,
    jac_inputs: set[str],
    jac_outputs: set[str],
):
    if _CACHE_SIZE <= 0:
        return jac_jit(inputs.model_dump(), tuple(jac_inputs), tuple(jac_outputs))
    inputs_dict = inputs.model_dump()
    _, f_lin = _linearize_and_cache(inputs_dict)
    dynamic_in, _ = eqx.partition(inputs_dict, eqx.is_array)
    return _jac_with_lin(f_lin, dynamic_in, tuple(jac_inputs), tuple(jac_outputs))


def jacobian_vector_product(
    inputs: InputSchema,
    jvp_inputs: set[str],
    jvp_outputs: set[str],
    tangent_vector: dict[str, Any],
):
    if _CACHE_SIZE <= 0:
        return jvp_jit(
            inputs.model_dump(),
            tuple(jvp_inputs),
            tuple(jvp_outputs),
            tangent_vector,
        )
    inputs_dict = inputs.model_dump()
    _, f_lin = _linearize_and_cache(inputs_dict)
    dynamic_in, _ = eqx.partition(inputs_dict, eqx.is_array)
    return _jvp_with_lin(
        f_lin, dynamic_in, tangent_vector, tuple(jvp_inputs), tuple(jvp_outputs)
    )


def vector_jacobian_product(
    inputs: InputSchema,
    vjp_inputs: set[str],
    vjp_outputs: set[str],
    cotangent_vector: dict[str, Any],
):
    if _CACHE_SIZE <= 0:
        return vjp_jit(
            inputs.model_dump(),
            tuple(vjp_inputs),
            tuple(vjp_outputs),
            cotangent_vector,
        )
    inputs_dict = inputs.model_dump()
    primal_out, f_lin = _linearize_and_cache(inputs_dict)
    dynamic_in, _ = eqx.partition(inputs_dict, eqx.is_array)
    return _vjp_with_lin(
        f_lin,
        dynamic_in,
        primal_out,
        cotangent_vector,
        tuple(vjp_inputs),
        tuple(vjp_outputs),
    )


def abstract_eval(abstract_inputs):
    """Calculate output shape of apply from the shape of its inputs."""
    is_shapedtype_dict = lambda x: type(x) is dict and (x.keys() == {"shape", "dtype"})
    is_shapedtype_struct = lambda x: isinstance(x, jax.ShapeDtypeStruct)

    jaxified_inputs = jax.tree.map(
        lambda x: jax.ShapeDtypeStruct(**x) if is_shapedtype_dict(x) else x,
        abstract_inputs.model_dump(),
        is_leaf=is_shapedtype_dict,
    )
    dynamic_inputs, static_inputs = eqx.partition(
        jaxified_inputs, filter_spec=is_shapedtype_struct
    )

    def wrapped_apply(dynamic_inputs):
        inputs = eqx.combine(static_inputs, dynamic_inputs)
        return apply_jit(inputs)

    jax_shapes = jax.eval_shape(wrapped_apply, dynamic_inputs)
    return jax.tree.map(
        lambda x: (
            {"shape": x.shape, "dtype": str(x.dtype)} if is_shapedtype_struct(x) else x
        ),
        jax_shapes,
        is_leaf=is_shapedtype_struct,
    )


#
# Helper functions
#
# The _{jvp,vjp,jac}_with_lin helpers run when caching is enabled and reuse
# the cached linearization. The _jit helpers below are used when caching is
# disabled and compute everything from the forward pass on each call.
#


@eqx.filter_jit
def _jvp_with_lin(
    f_lin,
    dynamic_in: dict,
    tangent_vector: dict,
    jvp_inputs: tuple[str],
    jvp_outputs: tuple[str],
):
    zero_in = jax.tree.map(jnp.zeros_like, dynamic_in)
    projected = filter_func(f_lin, zero_in, jvp_outputs)
    return projected(tangent_vector)


@eqx.filter_jit
def _vjp_with_lin(
    f_lin,
    dynamic_in: dict,
    primal_out: dict,
    cotangent_vector: dict,
    vjp_inputs: tuple[str],
    vjp_outputs: tuple[str],
):
    zero_out = jax.tree.map(jnp.zeros_like, eqx.filter(primal_out, eqx.is_array))
    f_trans = jax.linear_transpose(f_lin, dynamic_in)

    def _trans_single(ct_out):
        (ct_in,) = f_trans(ct_out)
        return ct_in

    projected = filter_func(_trans_single, zero_out, vjp_inputs)
    return projected(cotangent_vector)


@eqx.filter_jit
def _jac_with_lin(
    f_lin,
    dynamic_in: dict,
    jac_inputs: tuple[str],
    jac_outputs: tuple[str],
):
    # Reverse-mode by default (cheaper when you have more inputs than outputs,
    # e.g. loss gradients). Swap `jacrev` for `jacfwd` for forward-mode.
    zero_in = jax.tree.map(jnp.zeros_like, dynamic_in)
    projected = filter_func(f_lin, zero_in, jac_outputs)
    flat_zero_in = flatten_with_paths(zero_in, jac_inputs)
    return jax.jacrev(projected)(flat_zero_in)


@eqx.filter_jit
def jac_jit(
    inputs: dict,
    jac_inputs: tuple[str],
    jac_outputs: tuple[str],
):
    filtered_apply = filter_func(apply_jit, inputs, jac_outputs)
    return jax.jacrev(filtered_apply)(
        flatten_with_paths(inputs, include_paths=jac_inputs)
    )


@eqx.filter_jit
def jvp_jit(
    inputs: dict, jvp_inputs: tuple[str], jvp_outputs: tuple[str], tangent_vector: dict
):
    filtered_apply = filter_func(apply_jit, inputs, jvp_outputs)
    return jax.jvp(
        filtered_apply,
        [flatten_with_paths(inputs, include_paths=jvp_inputs)],
        [tangent_vector],
    )[1]


@eqx.filter_jit
def vjp_jit(
    inputs: dict,
    vjp_inputs: tuple[str],
    vjp_outputs: tuple[str],
    cotangent_vector: dict,
):
    filtered_apply = filter_func(apply_jit, inputs, vjp_outputs)
    _, vjp_func = jax.vjp(
        filtered_apply, flatten_with_paths(inputs, include_paths=vjp_inputs)
    )
    return vjp_func(cotangent_vector)[0]
