name: Auto update uv in Dockerfile

on:
  pull_request:

  workflow_dispatch: # Allows manual trigger

  schedule:
    - cron: "0 0 * * 1" # 12AM only on Mondays

env:
  DOCKERFILE_PATH: "tesseract_core/sdk/templates/Dockerfile.base"

jobs:
  auto-update-uv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: main

        # after this step runs it provides `uv-version` as an output
      - name: Install uv
        id: latest
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Extract current version
        id: current
        run: |
          uv_version=$(sed -n -E 's/^ENV UV_VERSION=(.*)/\1/p' < ${DOCKERFILE_PATH})
          echo "uv-version=${uv_version}" >> ${GITHUB_OUTPUT}
          git diff

      - name: Compare and update uv version
        id: compare-and-update
        if: steps.latest.outputs.uv-version != steps.current.outputs.uv-version
        env:
            NEW_VERSION: ${{ steps.latest.outputs.uv-version }}
        run: |
          sed -i -E "s/^(ENV UV_VERSION=).*/\1${NEW_VERSION}/" ${DOCKERFILE_PATH}
          echo "updated=true" >> ${GITHUB_OUTPUT}

      - name: Create Pull Request
        id: create-pr-ok
        if: steps.compare-and-update.outputs.updated == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PL_PASTEURBOT_PAT_PUBLIC }}
          committer: PasteurBot <${{ vars.PL_PASTEURBOT_EMAIL }}>
          author: PasteurBot <${{ vars.PL_PASTEURBOT_EMAIL }}>
          commit-message: Update uv version in Dockerfile.base
          title: "chore: Update uv version in Dockerfile.base"
          branch: _bot/update-dockerfile-uv
          draft: true
          base: main
          body: |
            Dockerfile.base updated to latest uv version
