name: "CLA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: startsWith(github.event.comment.body, '@PasteurBot') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.PL_PASTEURBOT_PAT_PUBLIC }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/pasteurlabs/pasteur-oss-cla/blob/main/README.md'
          # Branch should not be protected
          branch: 'main'
          allowlist: 'dependabot[bot],PasteurBot'
          remote-organization-name: 'pasteurlabs'
          remote-repository-name: 'pasteur-oss-cla-signatures'
          create-file-commit-message: 'Creating file for storing CLA Signatures for tesseract-core'
          signed-commit-message: '$contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          custom-notsigned-prcomment: |
            Thank you for your contribution!
            Like many open-source projects, we ask that you sign our Contributor License Agreement before we can accept your contribution.
            You can do so by commenting `@PasteurBot I have read the CLA Document and I hereby sign the CLA` on this PR.
          custom-allsigned-prcomment: |
            All contributors have signed the CLA! Your contribution is now eligible for merging.
          custom-pr-sign-comment: |
            @PasteurBot I have read the CLA Document and I hereby sign the CLA
