name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

permissions:
  actions: write
  contents: read
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/tesseract-core/version1/cla.json'
          path-to-document: 'https://github.com/pasteurlabs/pasteur-oss-cla/blob/main/README.md'
          # Branch should not be protected
          branch: 'main'
          allowlist:

          remote-organization-name: 'pasteurlabs'
          remote-repository-name: 'pasteur-oss-cla-signatures'
          create-file-commit-message: 'Creating file for storing CLA Signatures'
          signed-commit-message: '$contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
