name: Test installation via pip

on:
  # run on PRs for validation
  pull_request:

jobs:
  test-pip-install:
    name: "Test pip install"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.10"
          - "3.13"
        dependencies:
          - "pinned"

        include:
          - os: ubuntu-latest
            python-version: "3.13"
            dependencies: "latest"

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          if [ "${{ matrix.dependencies }}" = "pinned" ]; then
            echo "Using pinned dependencies"
            pip install -r requirements.txt
            pip install --no-deps .
          else
            echo "Using latest dependencies"
            pip install .
          fi

      - name: Ensure CLI is available
        run: |
          tesseract --help

      - name: Ensure basic workflow works
        # Docker is only available on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          tesseract build examples/helloworld
          tesseract run helloworld apply '{"inputs": {"name": "GitHub Actions"}}'
