name: Test installation via pip

on:
    # run on PRs for validation
    pull_request:


jobs:
  test-pip-install:
    name: "Test pip install"
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.10"
          - "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
            # https://github.com/azure/login/tree/v2/?tab=readme-ov-file#creds
            creds: |
              {
                "clientId": "${{ secrets.PL_INTERNAL_TOOLS_AZ_CLIENT_ID }}",
                "clientSecret": "${{ secrets.PL_INTERNAL_TOOLS_AZ_CLIENT_SECRET }}",
                "subscriptionId": "${{ vars.PL_INTERNAL_TOOLS_AZ_CLIENT_SUB_ID }}",
                "tenantId": "${{ secrets.PL_INTERNAL_TOOLS_AZ_TENANT_ID }}"
              }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get Download Token
        run: echo "DOWNLOAD_TOKEN=$(az account get-access-token --query accessToken -o tsv)" >> $GITHUB_ENV

      - name: Install package
        run: |
          pip install -r requirements.txt \
            --index https://$DOWNLOAD_TOKEN@${{vars.PL_INTERNAL_PYPI_PULL_URL_NO_PROTOCOL}} \
            --extra-index-url https://pypi.org/simple
          pip install --no-deps .
